--first normal form is achieved (atomicity of attributes and no redundant attribute names)
--second normal form is achieved(1NF and there exist no non-prime attribute that depends on a subset of the candidate keys)
--3rd normal form (2NF and there exist no non-prime attributes which depend on other non-prime attributes, reducing redundancy)

DROP TABLE OWNEDCARS;
DROP TABLE OFFERS;
DROP TABLE CARS;
DROP TABLE USERSS;

CREATE TABLE USERSS(
USERNAME VARCHAR2(20),
PASSWORDD VARCHAR2(20),
PRIMARY KEY (USERNAME));

CREATE TABLE CARS(
CAR_ID VARCHAR2(20),
TYPEE CHAR(11),
SPIKY_WHEELS CHAR(1),
DURABILITY INTEGER,
SPEED INTEGER,
TRADE_VALUE NUMBER,
INLOT CHAR(1),
PRIMARY KEY (CAR_ID));

CREATE TABLE OFFERS(
BUYER VARCHAR2(20),
TARGET_CAR VARCHAR2(20),
INITIAL_PAYMENT NUMBER,
LOAN_DURATION INTEGER, --in months
PRIMARY KEY(BUYER, TARGET_CAR),
FOREIGN KEY(BUYER) REFERENCES USERSS(USERNAME),
FOREIGN KEY(TARGET_CAR) REFERENCES CARS(CAR_ID));

CREATE TABLE OWNEDCARS(
CAR_ID VARCHAR2(20),
OWNERR VARCHAR2(20),
REMAINING_PAYMENT NUMBER,
LOAN_DURATION NUMBER,
PRIMARY KEY(CAR_ID),
FOREIGN KEY (CAR_ID) REFERENCES CARS(CAR_ID),
FOREIGN KEY (OWNERR) REFERENCES USERSS(USERNAME));

SELECT CAR_ID, OWNERR,LOAN_DURATION, REMAINING_PAYMENT/LOAN_DURATION AS MONTHLY_RATE, REMAINING_PAYMENT AS TOTAL_REMAINING FROM OWNEDCARS;

--queriesINNER JOIN Customers ON Orders.CustomerID=Customers.CustomerID;

SELECT CAR_ID, INITIAL_PAYMENT AS y, LOAN_DURATION AS z, TRADE_VALUE AS x FROM OFFERS INNER JOIN CARS ON CAR_ID = TARGET_CAR WHERE TARGET_CAR = 'VroomyVroomer123';

UPDATE CARS SET INLOT = 't';

--viewLot
SELECT CAR_ID
FROM CARS
WHERE INLOT='t';

--confirm password
SELECT PASSWORDD
FROM USERSS
WHERE USERNAME = 'RegDaniel';

--search for username
SELECT USERNAME
FROM USERSS
WHERE USERNAME ='LordofDarkness';

--viewDebt
SELECT CAR_ID, REMAINING_PAYMENT
FROM OWNEDCARS 
WHERE OWNERR= 'Nux';

--viewOwned
SELECT CAR_ID
FROM OWNEDCARS 
WHERE OWNERR= 'Nux';

--accept an offer, moving it to OWNEDCARS
SELECT OFFERS.TARGET_CAR AS CAR_ID, OFFERS.BUYER AS OWNER,  CARS.TRADE_VALUE - OFFERS.INITIAL_PAYMENT AS REMAINING_PAYMENT, OFFERS.LOAN_DURATION  
FROM CARS, OFFERS
WHERE CARS.CAR_ID = OFFERS.TARGET_CAR;

--deletes all offers
DELETE FROM OFFERS
WHERE OFFERS.TARGET_CAR = 'VroomyVroomer321';

--removes car from lot
UPDATE CARS
SET CARS.INLOT = 'f'
WHERE CARS.CAR_ID = 'VroomyVroomer321';

INSERT INTO OWNEDCARS (CAR_ID, OWNERR, REMAINING_PAYMENT, LOAN_DURATION) VALUES ('TitaniumUnicycle','Nux',0, 0);



SELECT * FROM OWNEDCARS NATURAL JOIN CARS WHERE OWNERR = 'Nux';





DROP TABLE OWNEDCARS;

SELECT CAR_PRICE
FROM CARS, CUSTOMERS
WHERE CAR
